pipeline{
    agent any
    stages{
        stage('task1'){
            steps{
                sh 'echo "Hello phuongvd7"'
            }
            steps {
                sh 'echo "Hello task'
            }
        }
    }
  
}