pipeline{
    agent any
    stages{
        stage('task1'){
            steps{
                sh 'echo "Hello phuongvd7"'
            }           
        }
        stage('task2'){
            steps {
                sh 'echo "Hello task2"'
            }
        }
    }
  
}